export {
  ArchitectureGenomeSchema,
  GenomeArtifactSchema,
  AgentSchema,
  EdgeSchema,
  ModelConfigSchema,
  ProtocolsSchema,
  WatcherSchema,
  MemoryPolicySchema,
  MutationPolicySchema,
  StopCriteriaSchema,
  CognitiveModeSchema,
  InteractionSchema,
  CapabilitySchema,
  MutationTypeSchema,
  WatcherDimensionSchema,
  HumanApprovalSchema,
  PRIVILEGE_BEARING_MUTATIONS,
  type ArchitectureGenome,
  type ArchitectureGenomeInput,
  type GenomeArtifact,
  type AgentSpec,
  type EdgeSpec,
  type ModelConfig,
  type Protocols,
  type WatcherConfig,
  type WatcherDimension,
  type MemoryPolicy,
  type MutationPolicy,
  type MutationType,
  type StopCriteria,
  type CognitiveMode,
  type Interaction,
  type Capability,
  type HumanApprovalLevel,
} from "./schema.js";

export {
  parseGenome,
  validateGenome,
  checkInvariants,
  modelFamily,
  type ValidationIssue,
  type ValidationResult,
  type ParseOptions,
} from "./validate.js";

export {
  MutationPatchSchema,
  MutationPatchListSchema,
  applyPatches,
  assertPatchesAllowed,
  parsePatches,
  diffGenomes,
  isEmptyDiff,
  type MutationPatch,
  type MutationPatchInput,
  type MutationActor,
  type ApplyOptions,
  type ApplyResult,
  type GenomeDiff,
} from "./patches.js";

export {
  hashGenome,
  sameGenome,
  exportArtifact,
  importArtifact,
  serializeArtifact,
  type LineageInfo,
} from "./artifact.js";

export {
  TEMPLATES,
  loadTemplate,
  BALANCED_ANALYSIS,
  ADVERSARIAL_RESEARCH,
  RAPID_TRIAGE,
  type GenomeTemplate,
} from "./templates.js";
