/**
 * Regenerate the embedded copy of the migration files.
 *
 *   pnpm gen:migrations
 *
 * The `.sql` files remain the source of truth; this only mirrors them into a
 * module so the runtime never has to read them from disk. A test fails if the
 * two drift.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "packages/db/migrations");
const out = join(root, "packages/db/src/migrations.generated.ts");

const names = (await readdir(dir)).filter((f) => f.endsWith(".sql")).sort();
const entries = await Promise.all(
  names.map(async (name) => ({ name, body: await readFile(join(dir, name), "utf8") })),
);

const literal = (s: string) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

const file = `// GENERATED by \`pnpm gen:migrations\` — do not edit.
//
// The migration \`.sql\` files are the source of truth; this mirrors them so the
// runtime never reads the filesystem. Serverless bundlers ship the module graph,
// not arbitrary sibling directories, so a \`readdir\` at request time finds
// nothing once deployed. \`packages/db/test/migrations.test.ts\` fails if this
// copy drifts from the files.

export interface EmbeddedMigration {
  readonly name: string;
  readonly body: string;
}

export const EMBEDDED_MIGRATIONS: readonly EmbeddedMigration[] = [
${entries.map((e) => `  { name: ${JSON.stringify(e.name)}, body: ${literal(e.body)} },`).join("\n")}
];
`;

await writeFile(out, file, "utf8");
console.log(`wrote ${out} (${entries.length} migrations, ${file.length} bytes)`);
